User:
  type: object
  properties:
    id:
      type: string
      format: uuid
    firstName:
      type: string
    lastName:
      type: string
    email:
      type: string
      format: email
    phone:
      type: string
    role:
      type: string
      enum: [user, admin, expert]
    dni:
      type: string
    birthdate:
      type: string
      format: date
    address:
      type: string
    postalCode:
      type: string
    dniImg:
      type: string
    profileImg:
      type: string
    profiles:
      type: array
      items:
        $ref: '../../profiles/schemas/profilesSwaggerSchema.yml#/Profile'
    requests:
      type: array
      items:
        $ref: '../../requests/schemas/requestsSwaggerSchema.yml#/Request'

CreateUser:
  type: object
  required:
    - firstName
    - lastName
    - email
    - password
    - dni
    - birthdate
    - address
  properties:
    firstName:
      type: string
    lastName:
      type: string
    email:
      type: string
      format: email
    phone:
      type: string
    password:
      type: string
      minLength: 6
    dni:
      type: string
    birthdate:
      type: string
      format: date
    address:
      type: string
    postalCode:
      type: string
    dniImg:
      type: string
    profileImg:
      type: string
    role:
      type: string
      enum: [user, admin, expert]
      default: user
    profiles:
      type: array
      items:
        type: string
        format: uuid

UpdateUser:
  type: object
  properties:
    firstName:
      type: string
    lastName:
      type: string
    email:
      type: string
      format: email
    phone:
      type: string
    address:
      type: string
    postalCode:
      type: string
    dniImg:
      type: string
    profileImg:
      type: string
