Login:
  type: object
  required:
    - email
    - password
  properties:
    email:
      type: string
      format: email
    password:
      type: string

AuthResponse:
  type: object
  properties:
    user:
      type: object
      properties:
        id:
          type: string
          format: uuid
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        phone:
          type: string
        role:
          type: string
        dni:
          type: string
        birthdate:
          type: string
        address:
          type: string
        postalCode:
          type: string
        dniImg:
          type: string
        profileImg:
          type: string
    token:
      type: string
